---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00aa9d3df94c6c354
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install python3-flask -y
          sudo apt install python3-pip -y
          sudo pip3 install boto3 requests
          git clone https://github.com/goreliks/cc_play_2.git
          cd cc_play_2
          export FLASK_APP=app.py
          nohup flask run --host=0.0.0.0 &
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00aa9d3df94c6c354
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install python3-flask -y
          sudo apt install python3-pip -y
          sudo pip3 install boto3 requests
          git clone https://github.com/goreliks/cc_play_2.git
          cd cc_play_2
          export FLASK_APP=app.py
          nohup flask run --host=0.0.0.0 &
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
